[project]
name = "cosmic-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "pytest>=8.3.4",
    "sqlalchemy>=2.0.38",
]
